[package]
name = "LightweightTwinCATAUTDServer"
version = "14.2.2"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"

description = "LightweightTwinCATAUTDServer"
repository = "https://github.com/shinolab/autd3"
readme = "../README.md"
keywords = ["autd"]

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
autd3-protobuf = { path = "../../src/autd3-protobuf", version = "14.2.2" }
autd3-link-twincat = { path = "../../src/autd3-link-twincat", version = "14.2.2" }
autd3-core = { path = "../../src/autd3-core", version = "14.2.2" }
anyhow = "1.0.72"
ctrlc = "3.3.0"
spdlog-rs = "0.3.8"
tonic = "0.9.2"
