[package]
name = "autd3capi"
version = "18.0.1"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
autd3capi-def = { path = "../autd3capi-def" }
autd3-driver = { path = "../../src/autd3-driver" }

[build-dependencies]
autd3capi-wrapper-generator = { path = "../autd3capi-wrapper-generator" }

[features]
single_float = ["autd3capi-def/single_float", "autd3-driver/single_float"]
use_meter = ["autd3capi-def/use_meter", "autd3-driver/use_meter"]

[dev-dependencies]
assert_approx_eq = "1.1.0"
