[package]
name = "autd3capi-def"
version = "17.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
async-ffi = "0.5.0"
autd3capi-common = { path = "../autd3capi-common" }
tokio = { version = "1.33.0", features = ["rt-multi-thread"] }

[build-dependencies]
wrapper-generator = { path = "../wrapper-generator" }

[features]
single_float = ["autd3capi-common/single_float"]
use_meter = ["autd3capi-common/use_meter"]
