[package]
name = "autd3capi-def"
version = "17.0.1"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
autd3capi-common = { path = "../autd3capi-common" }

[build-dependencies]
wrapper-generator = { path = "../wrapper-generator" }

[features]
single_float = ["autd3capi-common/single_float"]
use_meter = ["autd3capi-common/use_meter"]

[dev-dependencies]
assert_approx_eq = "1.1.0"
memoffset = "0.9.0"
