[package]
name = "sample"
version = "2.6.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
autd3 = "2.6.7"
autd3-link-soem = "2.6.7"
