[package]
name = "sample"
version = "2.6.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autd3 = "2.6.5"
autd3-link-soem = "2.6.5"
