[package]
name = "autd3-examples"
version = "15.3.1"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
edition = "2021"
license = "MIT"

[[bin]]
name = "debug"
path = "src/debug.rs"

[[bin]]
name = "group_gain"
path = "src/group_gain.rs"

[[bin]]
name = "async"
path = "src/async.rs"
required-features = ["async"]

[[bin]]
name = "soem"
path = "src/soem.rs"
required-features = ["soem"]

[[bin]]
name = "remote_soem"
path = "src/remote_soem.rs"
required-features = ["remote_soem"]

[[bin]]
name = "twincat"
path = "src/twincat.rs"
required-features = ["twincat"]

[[bin]]
name = "remote_twincat"
path = "src/remote_twincat.rs"
required-features = ["remote_twincat"]

[[bin]]
name = "simulator"
path = "src/simulator.rs"
required-features = ["simulator"]

[[bin]]
name = "visualizer"
path = "src/visualizer.rs"
required-features = ["visualizer"]

[[bin]]
name = "freq_config"
path = "src/freq_config.rs"

[[bin]]
name = "lightweight"
path = "src/lightweight.rs"
required-features = ["lightweight"]

[dependencies]
anyhow = "1.0.72"
autd3 = { path = "../autd3" }
autd3-driver = { path = "../autd3-driver" }
autd3-gain-holo = { path = "../autd3-gain-holo" }
autd3-link-simulator = { path = "../autd3-link-simulator", optional = true }
autd3-backend-cuda = { path = "../autd3-backend-cuda", optional = true }
autd3-link-soem = { path = "../autd3-link-soem", optional = true }
autd3-link-twincat = { path = "../autd3-link-twincat", optional = true }
autd3-link-visualizer = { path = "../autd3-link-visualizer", optional = true }
autd3-modulation-audio-file = { path = "../autd3-modulation-audio-file" }
autd3-protobuf = { path = "../autd3-protobuf", optional = true }
colored = "2.0.0"
tokio = { version = "1.29.0", features = ["macros", "rt-multi-thread"], optional = true }

[features]
default = []
async = ["tokio"]
simulator = ["autd3-link-simulator"]
soem = ["autd3-link-soem/local"]
remote_soem = ["autd3-link-soem/remote"]
twincat = ["autd3-link-twincat/local"]
remote_twincat = ["autd3-link-twincat/remote"]
visualizer = ["autd3-link-visualizer"]
gpu = ["autd3-link-visualizer/gpu"]
python = ["autd3-link-visualizer/python"]
lightweight = ["autd3-protobuf", "tokio"]
all = ["twincat", "remote_twincat", "soem", "remote_soem", "async", "lightweight", "simulator", "visualizer"]

cuda = ["autd3-backend-cuda"]
single_float = ["autd3/single_float"]
use_meter = ["autd3/use_meter"]
