name: build-cpp

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    name: check if files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/build-cpp.yml
            cpp/**/*.hpp
            cpp/**/*.cpp

  build:
    needs: check
    if: needs.check.outputs.status
    name: build-cpp-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-build
        with:
          os: ${{ matrix.os }}
          cuda: true

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './capi -> target'

      - name: Build capi on ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: |
          cd cpp
          ./build.ps1
      - name: Build capi on ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: |
          cd cpp
          chmod +x build.sh
          ./build.sh

      - name: Build C++ example on ${{ matrix.os }}
        run: |
          cd cpp/examples
          mkdir build
          cd build
          cmake .. -DAUTD_LOCAL_TEST=ON -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
          cmake --build . --config Release
        if: matrix.os == 'macos-latest'
      - name: Build C++ example on ${{ matrix.os }}
        run: |
          cd cpp/examples
          mkdir build
          cd build
          cmake .. -DAUTD_LOCAL_TEST=ON
          cmake --build . --config Release
        if: matrix.os != 'macos-latest'

      - name: Run C++ tests on ${{ matrix.os }}
        run: |
          cd cpp/tests
          mkdir build
          cd build
          cmake .. -DENABLE_BACKEND_CUDA=OFF
          cmake --build . --config Release
          ./Release/test_autd3.exe
        if: matrix.os == 'windows-latest'

      - name: Run C++ tests on ${{ matrix.os }}
        run: |
          cd cpp/tests
          mkdir build
          cd build
          cmake .. -DENABLE_BACKEND_CUDA=OFF -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
          cmake --build . --config Release
          ./test_autd3
        if: matrix.os != 'windows-latest'
