name: build-julia

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'dev'

jobs:
  test:
    name: build test on ${{ matrix.os }} with ${{ matrix.julia-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        julia-version: ['1.8.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Build Package
        if: matrix.os == 'windows-latest'
        run: julia -e 'using Pkg; Pkg.add(path=\".\", subdir=\"julia\"); Pkg.build(\"AUTD3\")'
      - name: Build Package
        if: matrix.os != 'windows-latest'
        run: julia -e 'using Pkg; Pkg.add(path=".", subdir="julia"); Pkg.build("AUTD3")'
