name: build-cs

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    name: check if files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/build-cs.yml
            dotnet/cs/*.cs
            dotnet/cs/**/*.cs

  build:
    needs: check
    if: needs.check.outputs.status
    name: build-cs-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}
          cuda: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './capi -> target'

      - name: Build capi
        run: |
          cd dotnet/cs
          ./build.ps1
        if: matrix.os == 'windows-latest'
      - name: Build capi
        run: |
          cd dotnet/cs
          chmod +x build.sh
          ./build.sh
        if: matrix.os != 'windows-latest'

      - name: Test library
        run: |
          cd dotnet/cs/tests
          dotnet test

      - name: Build example
        run: |
          dotnet nuget add source $pwd/dotnet/cs/src/bin/Release -n autd3sharp_local
          cd ./dotnet/cs/example
          dotnet build -c:Release
          cd ../../fs/example
          dotnet build -c:Release
