name: build-cpp

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  check:
    runs-on: ubuntu-latest
    name: check if files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/build-cpp.yml
            cpp/CMakeLists.txt
            cpp/**/CMakeLists.txt
            cpp/**/*.hpp
            cpp/**/*.cpp

  build:
    needs: check
    name: build-cpp-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        if: needs.check.outputs.status
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Setup
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}
          shaderc: false

      - name: Rust cache
        if: needs.check.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './capi -> target'

      - name: Build C++ library on ${{ matrix.os }}
        run: |
          python3 build.py cpp build --release --cmake-extra="-DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12"
        if: needs.check.outputs.status
      - name: Run C++ tests on ${{ matrix.os }}
        run: |
          python3 build.py cpp test --release --cmake-extra="-DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12"
        if: needs.check.outputs.status


  build-linux-arm32:
    needs: check
    name: build-cpp-linux-arm32
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: 'ubuntu-latest'
          arch: 'arm32'

      - name: Rust cache
        if: needs.check.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './capi -> target'

      - name: Build C++ library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py cpp build --arch arm32 --no-examples


  build-linux-aarch64:
    needs: check
    name: build-cpp-linux-aarch64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: 'ubuntu-latest'
          arch: 'aarch64'

      - name: Rust cache
        if: needs.check.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './capi -> target'

      - name: Build C++ library on ${{ matrix.os }}
        if: needs.check.outputs.status
        run: |
          python3 build.py cpp build --arch aarch64 --no-examples
