name: build-cpp

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: build-cpp-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: tj-actions/changed-files@v37
      id: changed-files
      with:
        files: |
          .github/workflows/build-cpp.yml
          cpp/**/*.hpp
          cpp/**/*.cpp
    - uses: Jimver/cuda-toolkit@v0.2.11
      if: steps.changed-files.outputs.modified_files && matrix.os == 'windows-latest'
      with:
        cuda: '12.2.0'
        method: 'network'
        sub-packages: '["nvcc", "cudart", "cublas_dev", "cusolver_dev"]'
    - name: install cuda
      if: steps.changed-files.outputs.modified_files && matrix.os == 'ubuntu-latest'
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
        sudo dpkg -i cuda-keyring_1.1-1_all.deb
        sudo apt-get update
        sudo apt-get -y install cuda-nvcc-12-2 libcublas-dev-12-2 libcusolver-dev-12-2
        echo "/usr/local/cuda/bin" >> $GITHUB_PATH
    - name: install aarch64 target on macos
      if: steps.changed-files.outputs.modified_files && matrix.os == 'macos-latest'
      run: |
        rustup target add aarch64-apple-darwin

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.changed-files.outputs.modified_files
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './capi -> target'
      if: steps.changed-files.outputs.modified_files

    - name: Build capi on ${{ matrix.os }}
      if: steps.changed-files.outputs.modified_files && matrix.os == 'windows-latest'
      run: |
        cd cpp
        ./build.ps1
    - name: Build capi on ${{ matrix.os }}
      if: steps.changed-files.outputs.modified_files && matrix.os != 'windows-latest'
      run: |
        cd cpp
        chmod +x build.sh
        ./build.sh
    - name: Build C++ example on ${{ matrix.os }}
      run: |
        cd cpp/examples
        mkdir build
        cd build
        cmake .. -DAUTD_LOCAL_TEST=ON -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12
        cmake --build . --config Release
      if: steps.changed-files.outputs.modified_files && matrix.os == 'macos-latest'
    - name: Build C++ example on ${{ matrix.os }}
      run: |
        cd cpp/examples
        mkdir build
        cd build
        cmake .. -DAUTD_LOCAL_TEST=ON
        cmake --build . --config Release
      if: steps.changed-files.outputs.modified_files && matrix.os != 'macos-latest'
    - name: Run C++ tests on ${{ matrix.os }}
      run: |
        cd cpp/tests
        mkdir build
        cd build
        cmake .. -DENABLE_BACKEND_CUDA=OFF
        cmake --build . --config Release
        ./Release/test_autd3.exe
      if: steps.changed-files.outputs.modified_files && matrix.os == 'windows-latest'
    - name: Run C++ tests on ${{ matrix.os }}
      run: |
        cd cpp/tests
        mkdir build
        cd build
        cmake .. -DENABLE_BACKEND_CUDA=OFF
        cmake --build . --config Release
        ./test_autd3
      if: steps.changed-files.outputs.modified_files && matrix.os != 'windows-latest'
