name: build

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]

env:
  CARGO_INCREMENTAL: 0

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: check if src files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: |
            .github/actions/setup-build/action.yml
            .github/workflows/build.yml
            src/**/*.rs
            src/*.toml
            src/**/*.toml
            src/**/*.proto

  build-src:
    needs: check-src
    name: build-src-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check-src.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}
          cuda: true
          shaderc: true
        
      - name: Rust cache
        if: needs.check-src.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src -> target'

      - name: Test src on ${{ matrix.os }}
        if: needs.check-src.outputs.status
        run: |
          python3 build.py build --all --release
          python3 build.py test --all --release --skip-cuda

  build-linux-arm32-src:
    needs: check-src
    name: build-src-linux-arm32
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check-src.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
          arch: 'arm32'
          cuda: false
          shaderc: false

      - name: Rust cache
        if: needs.check-src.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src -> target'

      - name: Test src on ${{ matrix.os }}
        if: needs.check-src.outputs.status
        run: |
          python3 build.py build --all --arch arm32 --release

  build-linux-aarch64-src:
    needs: check-src
    name: build-src-linux-aarch64
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check-src.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
          arch: 'aarch64'
          cuda: false
          shaderc: false

      - name: Rust cache
        if: needs.check-src.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src -> target'

      - name: Test src on ${{ matrix.os }}
        if: needs.check-src.outputs.status
        run: |
          python3 build.py build --all --arch aarch64 --release

  lint-src:
    needs: check-src
    name: lint-src
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check-src.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
          cuda: true
          shaderc: true

      - name: Rust cache
        if: needs.check-src.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src -> target'

      - name: lint src
        if: needs.check-src.outputs.status
        run: |
          python3 build.py lint --release

  check-server:
    runs-on: ubuntu-latest
    name: check if server files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: |
            server/**/*.rs
            server/**/*.toml
            server/**/*.ts
            server/**/*.svelte
            server/package.json

  build-server:
    needs: check-server
    name: build-server
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        if: needs.check-src.outputs.status
        uses: ./.github/actions/setup-build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ${{ matrix.os }}
          cuda: false
          shaderc: true

      - name: Rust cache
        if: needs.check-src.outputs.status
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './server/src-tauri -> target'

      - name: install dependencies (ubuntu only)
        if: needs.check-src.outputs.status && matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev

      - name: Sync node version and setup cache
        if: needs.check-src.outputs.status
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json
  
      - name: build server
        if: needs.check-src.outputs.status
        run: |
          python3 build.py server build
