name: Document check

on:
  push:
    branches:
      - 'develop'
  pull_request:
    types: [opened, reopened, review_requested]


jobs:
  check:
    runs-on: ubuntu-latest
    name: check if files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          files: |
            .github/actions/setup-mdbook.yml
            .github/workflows/doc-check.yml
            doc/book.toml
            doc/**/*.md
            doc/**/*.cpp
            doc/**/*.cs
            doc/**/*.py
            src/**/*.rs
            src/*.toml
            src/**/*.toml
            src/**/*.proto

  build-jp:
    needs: check
    name: doc-check-jp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdbook
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test book jp
        if: needs.check.outputs.status
        run: |
          python3 build.py doc test jp

  build-en:
    needs: check
    name: doc-check-en
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdbook
        if: needs.check.outputs.status
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test book en
        if: needs.check.outputs.status
        run: |
          python3 build.py doc test en
