name: Doxygen

on:
  push:
    branches: [ master, doc ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --force --recursive

    - name: Document check
      run: |
        cd tools/doc_checker
        cargo run
        cd ..

    - name: Doxygen
      uses: ./.github/actions/cmake-doxygen-actions
    - name: mv doxygen doc_build
      run: |
        mkdir -p doc_build
        sudo mv ./build/doc/html ./doc_build/api

    - uses: jontze/action-mdbook@v1
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        use-linkcheck: true
        use-opengh: true
    - name: Setup mdbook-katex
      uses: magicgh/mdbook-katex-action@v1
      with:
        version: 'latest'
    - run: |
        cd book
        MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
        MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
    - name: mv mdbook doc
      run: |
        mkdir -p doc_build/book
        sudo mv ./book/book/en/html ./doc_build/book/en
        sudo mv ./book/book/jp/html ./doc_build/book/jp

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doc_build
