name: Document

on:
  push:
    branches: [ doc ]  

jobs:
  check-cs:
    name: doc-check-sample-cs
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: build
      run: |
        dotnet build ./doc/samples/cs/cs.csproj -c:Release

  check-cpp:
    name: doc-check-sample-cpp
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd ./doc/samples/cpp
        mkdir build
        cd build
        cmake ..
        cmake --build .

  check-python:
    name: doc-check-sample-python
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: install deps
      run: |
        python -m pip install --upgrade pyautd3
        python -m pip install --upgrade numpy
    - name: build
      run: |
        cd doc/samples/python
        echo a | python main.py || true

  build:
    name: build-doc
    needs: [check-cs, check-cpp, check-python]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup mdbook
        uses: ./.github/actions/setup-mdbook
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          os: ubuntu-latest
      - name: Build book
        run: |
          cd ./doc
          MDBOOK_BOOK__src=src/en mdbook build --dest-dir book/en
          MDBOOK_BOOK__src=src/jp mdbook build --dest-dir book/jp
      - name: mv mdbook doc
        run: |
          mkdir -p doc_build/book
          sudo mv ./doc/book/en ./doc_build/book/en
          sudo mv ./doc/book/jp ./doc_build/book/jp
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc_build
          force_orphan: true
