name: test

on:
  push:
    tags-ignore:
      - v*
    branches:
      - 'test'

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps: 
    - uses: actions/checkout@v3
    - name: install compile tools
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev -y
      shell: bash
    - name: test
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p build && cd build
        cmake .. -DBUILD_ALL=ON -DBUILD_TEST=ON
        cmake --build . --config Release --parallel 8 --target test_autd3
        ./tests/test_autd3
    - name: test
      if: matrix.os == 'windows-latest'
      run: |
        mkdir build
        cd build
        cmake .. -DBUILD_ALL=ON -DBUILD_TEST=ON
        cmake --build . --config Release --parallel 8 --target test_autd3
        ./tests/Release/test_autd3.exe
